Add play icon
marezloum/final-project pull request #3
Opened 2022-07-21 10:50 UTC by marezloum

2022-07-21 11:07 UTC, parkourrunner requested changes

2022-07-21 11:07 UTC, parkourrunner commented on single-video.html
> +
Please remove this empty line.

2022-07-25 06:34 UTC, marezloum commented on single-video.html
> +
Done!

2022-07-25 13:33 UTC, alisalehi6990 approved these changes
LGTM, thanks.

2022-07-26 17:12 UTC, merged